name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  WEBAPP_NAME: 'M3U8 Downloader.sln'     # set this to your application's name
  WEBAPP_PACKAGE_PATH: 'published'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: add path
      run: echo "::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
    
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.1
      with:
        vs-version: "[16.4,16.9)"
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet packages
      run: nuget restore ${{ env.WEBAPP_NAME }}

    - name: Build
      run: msbuild ${{ env.WEBAPP_NAME }} /p:Configuration=Release

    - name: Publish to folder
      run: msbuild ${{ env.WEBAPP_NAME }} /p:Configuration=Release /p:DeployOnBuild=true /t:WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=${{ env._WEBAPP_PACKAGE_PATH }} /p:PackageAsSingleFile=false

    - name: Deploy to WebApp
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        publish-profile: ${{ secrets.WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.WEBAPP_PACKAGE_PATH }}

    - name: Publish artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.WEBAPP_PACKAGE_PATH }}
